## 7.1

In [420]:
import numpy as np
A = np.array([13,19,9,5,12,8,7,4,11,2,6,21])

In [421]:
def HOARE_PARTITION (A,p,r,noprint=True):
    x = A[p]
    i=p
    j=r
    
    if noprint == False:
        print ('Original______________________{}'.format(A))
    
    while i<j:
        
        
        
        while A[j]>=x and j>p:
            
            j = j - 1

          
        while A[i]<=x and i<r:
            #print(A[i])
            i=i+1


        if i<j:
            A[i],A[j] = A [j],A[i]
            
            if noprint == False:
                print ('Exchanging i= {} and j ={}     {}'.format(i,j,A))
            
        
    
    A[p],A[j] = A [j],A[p]
    if noprint == False:
        print ('Final_________________________{}'.format(A))
    return j

## 7.1.A

In [422]:
HOARE_PARTITION(A,0,len(A)-1,False)

Original______________________[13 19  9  5 12  8  7  4 11  2  6 21]
Exchanging i= 1 and j =10     [13  6  9  5 12  8  7  4 11  2 19 21]
Final_________________________[ 2  6  9  5 12  8  7  4 11 13 19 21]


9

## 7.1.E

In [423]:
def quicksort(A,p,r):
    if p<r:
        q=HOARE_PARTITION(A,p,r)
        quicksort(A,p,q)
        quicksort(A,q+1,r)
    

In [424]:
quicksort(A,0,len(A)-1)

In [425]:
A

array([ 2,  4,  5,  6,  7,  8,  9, 11, 12, 13, 19, 21])

## 7.2

In [426]:
def new_partition(A,p,r):
    
    x = A[r]
    i = p-1
    t = 0
    
    for j in range(p,r):

        
        if A[j]==x:
            i=i+1
            t=t+1 #count repeats
            A[i],A[j] = A [j],A[i]


        
        if A[j]<x:
            i=i+1
            A[i],A[j] = A [j],A[i]
            k=i
            for _ in range(t):
                A[k],A[k-1] = A[k-1],A[k]
                k=k-1     
    

    A[i+1],A[r] = A[r],A[i+1]    
    return (i-t+1,i+1)
    
    

In [427]:
A = np.array([ 6,  9,  5,  8,  7,  6,  6,  2,  6, 11, 12, 6])

In [428]:
new_partition(A,0,len(A)-1)

(2, 6)

In [429]:
print (A)

[ 5  2  6  6  6  6  6  7  9 11 12  8]


In [430]:
def new_quicksort(A,p,r):
    if p<r:
        t,q = new_partition(A,p,r)
        new_quicksort(A,p,t-1)
        new_quicksort(A,q+1,r)

In [431]:
A = np.array([ 6,  9,  5,  8,  7,  6,  6,  2,  6, 11, 12, 6])

In [432]:
new_quicksort(A,0,len(A)-1)

In [433]:
print (A)

[ 2  5  6  6  6  6  6  7  8  9 11 12]


In [434]:
def new_randomized_partition(A,p,r):
    i=np.random.randint(p,r)
    A[r],A[i] = A[i],A[r]
    return new_partition(A,p,r)
    

In [435]:
A = np.array([ 6,  9,  5,  8,  7,  6,  6,  2,  6, 11, 12, 6])
new_randomized_partition(A,0,len(A)-1)
print (A)

[ 5  2  6  6  6  6  6  7  9 11 12  8]


In [436]:
def new_randomized_quicksort(A,p,r):
    if p<r:
        t,q = new_randomized_partition(A,p,r)
        new_randomized_quicksort(A,p,t-1)
        new_randomized_quicksort(A,q+1,r)
        

In [437]:
A = np.array([ 6,  9,  5,  8,  7,  6,  6,  2,  6, 11, 12, 6])
new_randomized_quicksort(A,0,len(A)-1)
print (A)

[ 2  5  6  6  6  6  6  7  8  9 11 12]
